<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup Label="Microsoft">
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.400" />
    <PackageVersion Include="System.Configuration.ConfigurationManager" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.0" />
  </ItemGroup>
  <ItemGroup Label="Roslynator">
    <PackageVersion Include="Roslynator.Analyzers" Version="5.0.0" />
    <PackageVersion Include="Roslynator.CodeFixes" Version="5.0.0" />
  </ItemGroup>
</Project>
