//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Security.Application.SecurityRuntimeEngine.ConfigurationGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Security.Application.SecurityRuntimeEngine.ConfigurationGenerator.Prope" +
                            "rties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected files have been successfully analyzed, click &quot;Generate&quot; to generate the configuration file..
        /// </summary>
        public static string AnalysisCompleteMessage {
            get {
                return ResourceManager.GetString("AnalysisCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Complete.
        /// </summary>
        public static string AnalysisCompleteTitle {
            get {
                return ResourceManager.GetString("AnalysisCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file cannot be generated as the assembly analysis not complete. Click &quot;Analysis&quot; button first and then try again..
        /// </summary>
        public static string AnalysisNotCompletedMessage {
            get {
                return ResourceManager.GetString("AnalysisNotCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis not completed.
        /// </summary>
        public static string AnalysisNotCompletedTitle {
            get {
                return ResourceManager.GetString("AnalysisNotCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occured during assembly analysis..
        /// </summary>
        public static string AnalysisUnknownErrorMessage {
            get {
                return ResourceManager.GetString("AnalysisUnknownErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze.
        /// </summary>
        public static string btnAnalyze {
            get {
                return ResourceManager.GetString("btnAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts the analysis of selected ASP.NET assemblies..
        /// </summary>
        public static string btnAnalyze_Help {
            get {
                return ResourceManager.GetString("btnAnalyze_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Browse.
        /// </summary>
        public static string btnBrowse {
            get {
                return ResourceManager.GetString("btnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens up dialog box to select one or more ASP.NET assemblies for analysis..
        /// </summary>
        public static string btnBrowse_Help {
            get {
                return ResourceManager.GetString("btnBrowse_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the utility..
        /// </summary>
        public static string btnClose_Help {
            get {
                return ResourceManager.GetString("btnClose_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string btnGenerate {
            get {
                return ResourceManager.GetString("btnGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates the configuration file after the analysis. &quot;Analyze&quot; must be clicked before clicking this button..
        /// </summary>
        public static string btnGenerate_Help {
            get {
                return ResourceManager.GetString("btnGenerate_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Double Encoding Protection.
        /// </summary>
        public static string chkDoubleEncoding {
            get {
                return ResourceManager.GetString("chkDoubleEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides double encoding protection for controls where if the control&apos;s property is already encoded, SRE will automatically detect and encode the data appropriately..
        /// </summary>
        public static string chkDoubleEncoding_Help {
            get {
                return ResourceManager.GetString("chkDoubleEncoding_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode Derived Controls.
        /// </summary>
        public static string chkEncodeDerivedControls {
            get {
                return ResourceManager.GetString("chkEncodeDerivedControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encodes controls which are derived from the controls in the configuration. .
        /// </summary>
        public static string chkEncodeDerivedControls_Help {
            get {
                return ResourceManager.GetString("chkEncodeDerivedControls_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark AntiXss Output (select a color from the dropdown list).
        /// </summary>
        public static string chkMarkOutput {
            get {
                return ResourceManager.GetString("chkMarkOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encloses antixss module&apos;s output with aditional html element to help users visually distinguish encoded data. DO NOT SELECT THIS OPTION FOR PRODUCTION APPLICATIONS..
        /// </summary>
        public static string chkMarkOutput_Help {
            get {
                return ResourceManager.GetString("chkMarkOutput_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Name.
        /// </summary>
        public static string clmnControl {
            get {
                return ResourceManager.GetString("clmnControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Type.
        /// </summary>
        public static string clmnControlType {
            get {
                return ResourceManager.GetString("clmnControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Name.
        /// </summary>
        public static string clmnPage {
            get {
                return ResourceManager.GetString("clmnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file has been successfully generated..
        /// </summary>
        public static string ConfigGenCompleteMessage {
            get {
                return ResourceManager.GetString("ConfigGenCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration File.
        /// </summary>
        public static string ConfigGenCompleteTitle {
            get {
                return ResourceManager.GetString("ConfigGenCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occured during configuration file generation..
        /// </summary>
        public static string ConfigGenUnknownErrorMessage {
            get {
                return ResourceManager.GetString("ConfigGenUnknownErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an ASP.NET assembly.
        /// </summary>
        public static string dlgAssemblyTitle {
            get {
                return ResourceManager.GetString("dlgAssemblyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to save the configuration file..
        /// </summary>
        public static string dlgGenConfigDescription {
            get {
                return ResourceManager.GetString("dlgGenConfigDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be found in the specified path..
        /// </summary>
        public static string FileNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("FileNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string FileNotFoundExceptionTitle {
            get {
                return ResourceManager.GetString("FileNotFoundExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file already exists in the selected folder. Do you want to overwrite the configuration file?.
        /// </summary>
        public static string FileOverwriteMessage {
            get {
                return ResourceManager.GetString("FileOverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite configuration file.
        /// </summary>
        public static string FileOverwriteTitle {
            get {
                return ResourceManager.GetString("FileOverwriteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Generator for SRE.
        /// </summary>
        public static string frmMain {
            get {
                return ResourceManager.GetString("frmMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string grpAnalysis {
            get {
                return ResourceManager.GetString("grpAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the list of controls that need encoding from the selected assemblies..
        /// </summary>
        public static string grpAnalysis_Help {
            get {
                return ResourceManager.GetString("grpAnalysis_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string grpOptions {
            get {
                return ResourceManager.GetString("grpOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module options which provide additional functionality. Check individual checkboxes for more information..
        /// </summary>
        public static string grpOptions_Help {
            get {
                return ResourceManager.GetString("grpOptions_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse and select ASP.NET assemblies to generate the configuration file.  Click &quot;Browse&quot; to select an assembly for analysis and click &quot;Analyze&quot; to inspect the assembly for identifying controls that need encoding. Make sure that all the assembly references are in the same folder. Click the Help button in the title bar, then click a control to see a Help tooltip for the control..
        /// </summary>
        public static string lblMainText {
            get {
                return ResourceManager.GetString("lblMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays general information on this utility..
        /// </summary>
        public static string lblMainText_Help {
            get {
                return ResourceManager.GetString("lblMainText_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET Assembly:.
        /// </summary>
        public static string lblProjectDir {
            get {
                return ResourceManager.GetString("lblProjectDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET assembly.
        /// </summary>
        public static string lblProjectDir_Help {
            get {
                return ResourceManager.GetString("lblProjectDir_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the list of controls that need encoding from the selected assemblies..
        /// </summary>
        public static string lvwAnalysis_Help {
            get {
                return ResourceManager.GetString("lvwAnalysis_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File has been selected for analysis, click &quot;Browse&quot; to select assembly file(s)..
        /// </summary>
        public static string NoFileSelectedErrorMessage {
            get {
                return ResourceManager.GetString("NoFileSelectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File Selected.
        /// </summary>
        public static string NoFileSelectedErrorTitle {
            get {
                return ResourceManager.GetString("NoFileSelectedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the path of ASP.NET assemblies used in the analysis. You can enter multiple file names separated by a comma or click &quot;Browse&quot; to select assembly files(s)..
        /// </summary>
        public static string txtAssemblyFile_Help {
            get {
                return ResourceManager.GetString("txtAssemblyFile_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string UnknownErrorTitle {
            get {
                return ResourceManager.GetString("UnknownErrorTitle", resourceCulture);
            }
        }
    }
}
